// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zetasql/public/simple_table.proto

#include "zetasql/public/simple_table.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace zetasql {
constexpr SimpleAnonymizationInfoProto::SimpleAnonymizationInfoProto(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : userid_column_name_(){}
struct SimpleAnonymizationInfoProtoDefaultTypeInternal {
  constexpr SimpleAnonymizationInfoProtoDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SimpleAnonymizationInfoProtoDefaultTypeInternal() {}
  union {
    SimpleAnonymizationInfoProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SimpleAnonymizationInfoProtoDefaultTypeInternal _SimpleAnonymizationInfoProto_default_instance_;
constexpr SimpleTableProto::SimpleTableProto(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : column_()
  , primary_key_column_index_()
  , name_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , name_in_catalog_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , anonymization_info_(nullptr)
  , serialization_id_(int64_t{0})
  , is_value_table_(false)
  , allow_anonymous_column_name_(false)
  , allow_duplicate_column_names_(false){}
struct SimpleTableProtoDefaultTypeInternal {
  constexpr SimpleTableProtoDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SimpleTableProtoDefaultTypeInternal() {}
  union {
    SimpleTableProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SimpleTableProtoDefaultTypeInternal _SimpleTableProto_default_instance_;
constexpr SimpleColumnProto::SimpleColumnProto(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : name_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , type_(nullptr)
  , annotation_map_(nullptr)
  , is_pseudo_column_(false)
  , is_writable_column_(true){}
struct SimpleColumnProtoDefaultTypeInternal {
  constexpr SimpleColumnProtoDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SimpleColumnProtoDefaultTypeInternal() {}
  union {
    SimpleColumnProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SimpleColumnProtoDefaultTypeInternal _SimpleColumnProto_default_instance_;
}  // namespace zetasql
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_zetasql_2fpublic_2fsimple_5ftable_2eproto[3];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_zetasql_2fpublic_2fsimple_5ftable_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_zetasql_2fpublic_2fsimple_5ftable_2eproto = nullptr;

const uint32_t TableStruct_zetasql_2fpublic_2fsimple_5ftable_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::zetasql::SimpleAnonymizationInfoProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::zetasql::SimpleAnonymizationInfoProto, userid_column_name_),
  PROTOBUF_FIELD_OFFSET(::zetasql::SimpleTableProto, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::zetasql::SimpleTableProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::zetasql::SimpleTableProto, name_),
  PROTOBUF_FIELD_OFFSET(::zetasql::SimpleTableProto, serialization_id_),
  PROTOBUF_FIELD_OFFSET(::zetasql::SimpleTableProto, is_value_table_),
  PROTOBUF_FIELD_OFFSET(::zetasql::SimpleTableProto, column_),
  PROTOBUF_FIELD_OFFSET(::zetasql::SimpleTableProto, primary_key_column_index_),
  PROTOBUF_FIELD_OFFSET(::zetasql::SimpleTableProto, name_in_catalog_),
  PROTOBUF_FIELD_OFFSET(::zetasql::SimpleTableProto, allow_anonymous_column_name_),
  PROTOBUF_FIELD_OFFSET(::zetasql::SimpleTableProto, allow_duplicate_column_names_),
  PROTOBUF_FIELD_OFFSET(::zetasql::SimpleTableProto, anonymization_info_),
  0,
  3,
  4,
  ~0u,
  ~0u,
  1,
  5,
  6,
  2,
  PROTOBUF_FIELD_OFFSET(::zetasql::SimpleColumnProto, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::zetasql::SimpleColumnProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::zetasql::SimpleColumnProto, name_),
  PROTOBUF_FIELD_OFFSET(::zetasql::SimpleColumnProto, type_),
  PROTOBUF_FIELD_OFFSET(::zetasql::SimpleColumnProto, is_pseudo_column_),
  PROTOBUF_FIELD_OFFSET(::zetasql::SimpleColumnProto, is_writable_column_),
  PROTOBUF_FIELD_OFFSET(::zetasql::SimpleColumnProto, annotation_map_),
  0,
  1,
  3,
  4,
  2,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::zetasql::SimpleAnonymizationInfoProto)},
  { 7, 22, -1, sizeof(::zetasql::SimpleTableProto)},
  { 31, 42, -1, sizeof(::zetasql::SimpleColumnProto)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::zetasql::_SimpleAnonymizationInfoProto_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::zetasql::_SimpleTableProto_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::zetasql::_SimpleColumnProto_default_instance_),
};

const char descriptor_table_protodef_zetasql_2fpublic_2fsimple_5ftable_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n!zetasql/public/simple_table.proto\022\007zet"
  "asql\032\037zetasql/public/annotation.proto\032\031z"
  "etasql/public/type.proto\":\n\034SimpleAnonym"
  "izationInfoProto\022\032\n\022userid_column_name\030\001"
  " \003(\t\"\307\002\n\020SimpleTableProto\022\014\n\004name\030\001 \001(\t\022"
  "\030\n\020serialization_id\030\002 \001(\003\022\026\n\016is_value_ta"
  "ble\030\003 \001(\010\022*\n\006column\030\004 \003(\0132\032.zetasql.Simp"
  "leColumnProto\022 \n\030primary_key_column_inde"
  "x\030\t \003(\005\022\027\n\017name_in_catalog\030\005 \001(\t\022#\n\033allo"
  "w_anonymous_column_name\030\006 \001(\010\022$\n\034allow_d"
  "uplicate_column_names\030\007 \001(\010\022A\n\022anonymiza"
  "tion_info\030\010 \001(\0132%.zetasql.SimpleAnonymiz"
  "ationInfoProto\"\264\001\n\021SimpleColumnProto\022\014\n\004"
  "name\030\001 \001(\t\022 \n\004type\030\002 \001(\0132\022.zetasql.TypeP"
  "roto\022\030\n\020is_pseudo_column\030\003 \001(\010\022 \n\022is_wri"
  "table_column\030\004 \001(\010:\004true\0223\n\016annotation_m"
  "ap\030\005 \001(\0132\033.zetasql.AnnotationMapProtoB\'\n"
  "\022com.google.zetasqlB\021SimpleTableProtos"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_zetasql_2fpublic_2fsimple_5ftable_2eproto_deps[2] = {
  &::descriptor_table_zetasql_2fpublic_2fannotation_2eproto,
  &::descriptor_table_zetasql_2fpublic_2ftype_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_zetasql_2fpublic_2fsimple_5ftable_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_zetasql_2fpublic_2fsimple_5ftable_2eproto = {
  false, false, 718, descriptor_table_protodef_zetasql_2fpublic_2fsimple_5ftable_2eproto, "zetasql/public/simple_table.proto", 
  &descriptor_table_zetasql_2fpublic_2fsimple_5ftable_2eproto_once, descriptor_table_zetasql_2fpublic_2fsimple_5ftable_2eproto_deps, 2, 3,
  schemas, file_default_instances, TableStruct_zetasql_2fpublic_2fsimple_5ftable_2eproto::offsets,
  file_level_metadata_zetasql_2fpublic_2fsimple_5ftable_2eproto, file_level_enum_descriptors_zetasql_2fpublic_2fsimple_5ftable_2eproto, file_level_service_descriptors_zetasql_2fpublic_2fsimple_5ftable_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_zetasql_2fpublic_2fsimple_5ftable_2eproto_getter() {
  return &descriptor_table_zetasql_2fpublic_2fsimple_5ftable_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_zetasql_2fpublic_2fsimple_5ftable_2eproto(&descriptor_table_zetasql_2fpublic_2fsimple_5ftable_2eproto);
namespace zetasql {

// ===================================================================

class SimpleAnonymizationInfoProto::_Internal {
 public:
};

SimpleAnonymizationInfoProto::SimpleAnonymizationInfoProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  userid_column_name_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:zetasql.SimpleAnonymizationInfoProto)
}
SimpleAnonymizationInfoProto::SimpleAnonymizationInfoProto(const SimpleAnonymizationInfoProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      userid_column_name_(from.userid_column_name_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:zetasql.SimpleAnonymizationInfoProto)
}

inline void SimpleAnonymizationInfoProto::SharedCtor() {
}

SimpleAnonymizationInfoProto::~SimpleAnonymizationInfoProto() {
  // @@protoc_insertion_point(destructor:zetasql.SimpleAnonymizationInfoProto)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void SimpleAnonymizationInfoProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SimpleAnonymizationInfoProto::ArenaDtor(void* object) {
  SimpleAnonymizationInfoProto* _this = reinterpret_cast< SimpleAnonymizationInfoProto* >(object);
  (void)_this;
}
void SimpleAnonymizationInfoProto::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SimpleAnonymizationInfoProto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SimpleAnonymizationInfoProto::Clear() {
// @@protoc_insertion_point(message_clear_start:zetasql.SimpleAnonymizationInfoProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  userid_column_name_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SimpleAnonymizationInfoProto::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated string userid_column_name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_userid_column_name();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            #ifndef NDEBUG
            ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "zetasql.SimpleAnonymizationInfoProto.userid_column_name");
            #endif  // !NDEBUG
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SimpleAnonymizationInfoProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:zetasql.SimpleAnonymizationInfoProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string userid_column_name = 1;
  for (int i = 0, n = this->_internal_userid_column_name_size(); i < n; i++) {
    const auto& s = this->_internal_userid_column_name(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "zetasql.SimpleAnonymizationInfoProto.userid_column_name");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:zetasql.SimpleAnonymizationInfoProto)
  return target;
}

size_t SimpleAnonymizationInfoProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:zetasql.SimpleAnonymizationInfoProto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string userid_column_name = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(userid_column_name_.size());
  for (int i = 0, n = userid_column_name_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      userid_column_name_.Get(i));
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SimpleAnonymizationInfoProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SimpleAnonymizationInfoProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SimpleAnonymizationInfoProto::GetClassData() const { return &_class_data_; }

void SimpleAnonymizationInfoProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<SimpleAnonymizationInfoProto *>(to)->MergeFrom(
      static_cast<const SimpleAnonymizationInfoProto &>(from));
}


void SimpleAnonymizationInfoProto::MergeFrom(const SimpleAnonymizationInfoProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:zetasql.SimpleAnonymizationInfoProto)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  userid_column_name_.MergeFrom(from.userid_column_name_);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SimpleAnonymizationInfoProto::CopyFrom(const SimpleAnonymizationInfoProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:zetasql.SimpleAnonymizationInfoProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SimpleAnonymizationInfoProto::IsInitialized() const {
  return true;
}

void SimpleAnonymizationInfoProto::InternalSwap(SimpleAnonymizationInfoProto* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  userid_column_name_.InternalSwap(&other->userid_column_name_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SimpleAnonymizationInfoProto::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_zetasql_2fpublic_2fsimple_5ftable_2eproto_getter, &descriptor_table_zetasql_2fpublic_2fsimple_5ftable_2eproto_once,
      file_level_metadata_zetasql_2fpublic_2fsimple_5ftable_2eproto[0]);
}

// ===================================================================

class SimpleTableProto::_Internal {
 public:
  using HasBits = decltype(std::declval<SimpleTableProto>()._has_bits_);
  static void set_has_name(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_serialization_id(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_is_value_table(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_name_in_catalog(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_allow_anonymous_column_name(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_allow_duplicate_column_names(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static const ::zetasql::SimpleAnonymizationInfoProto& anonymization_info(const SimpleTableProto* msg);
  static void set_has_anonymization_info(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

const ::zetasql::SimpleAnonymizationInfoProto&
SimpleTableProto::_Internal::anonymization_info(const SimpleTableProto* msg) {
  return *msg->anonymization_info_;
}
SimpleTableProto::SimpleTableProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  column_(arena),
  primary_key_column_index_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:zetasql.SimpleTableProto)
}
SimpleTableProto::SimpleTableProto(const SimpleTableProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_),
      column_(from.column_),
      primary_key_column_index_(from.primary_key_column_index_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_name()) {
    name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_name(), 
      GetArenaForAllocation());
  }
  name_in_catalog_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    name_in_catalog_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_name_in_catalog()) {
    name_in_catalog_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_name_in_catalog(), 
      GetArenaForAllocation());
  }
  if (from._internal_has_anonymization_info()) {
    anonymization_info_ = new ::zetasql::SimpleAnonymizationInfoProto(*from.anonymization_info_);
  } else {
    anonymization_info_ = nullptr;
  }
  ::memcpy(&serialization_id_, &from.serialization_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&allow_duplicate_column_names_) -
    reinterpret_cast<char*>(&serialization_id_)) + sizeof(allow_duplicate_column_names_));
  // @@protoc_insertion_point(copy_constructor:zetasql.SimpleTableProto)
}

inline void SimpleTableProto::SharedCtor() {
name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
name_in_catalog_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  name_in_catalog_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&anonymization_info_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&allow_duplicate_column_names_) -
    reinterpret_cast<char*>(&anonymization_info_)) + sizeof(allow_duplicate_column_names_));
}

SimpleTableProto::~SimpleTableProto() {
  // @@protoc_insertion_point(destructor:zetasql.SimpleTableProto)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void SimpleTableProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  name_in_catalog_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete anonymization_info_;
}

void SimpleTableProto::ArenaDtor(void* object) {
  SimpleTableProto* _this = reinterpret_cast< SimpleTableProto* >(object);
  (void)_this;
}
void SimpleTableProto::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SimpleTableProto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SimpleTableProto::Clear() {
// @@protoc_insertion_point(message_clear_start:zetasql.SimpleTableProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  column_.Clear();
  primary_key_column_index_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      name_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      name_in_catalog_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(anonymization_info_ != nullptr);
      anonymization_info_->Clear();
    }
  }
  if (cached_has_bits & 0x00000078u) {
    ::memset(&serialization_id_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&allow_duplicate_column_names_) -
        reinterpret_cast<char*>(&serialization_id_)) + sizeof(allow_duplicate_column_names_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SimpleTableProto::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "zetasql.SimpleTableProto.name");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional int64 serialization_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_serialization_id(&has_bits);
          serialization_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool is_value_table = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _Internal::set_has_is_value_table(&has_bits);
          is_value_table_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .zetasql.SimpleColumnProto column = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_column(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      // optional string name_in_catalog = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_name_in_catalog();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "zetasql.SimpleTableProto.name_in_catalog");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool allow_anonymous_column_name = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _Internal::set_has_allow_anonymous_column_name(&has_bits);
          allow_anonymous_column_name_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool allow_duplicate_column_names = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _Internal::set_has_allow_duplicate_column_names(&has_bits);
          allow_duplicate_column_names_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .zetasql.SimpleAnonymizationInfoProto anonymization_info = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          ptr = ctx->ParseMessage(_internal_mutable_anonymization_info(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated int32 primary_key_column_index = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          ptr -= 1;
          do {
            ptr += 1;
            _internal_add_primary_key_column_index(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<72>(ptr));
        } else if (static_cast<uint8_t>(tag) == 74) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_primary_key_column_index(), ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SimpleTableProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:zetasql.SimpleTableProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "zetasql.SimpleTableProto.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // optional int64 serialization_id = 2;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(2, this->_internal_serialization_id(), target);
  }

  // optional bool is_value_table = 3;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(3, this->_internal_is_value_table(), target);
  }

  // repeated .zetasql.SimpleColumnProto column = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_column_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, this->_internal_column(i), target, stream);
  }

  // optional string name_in_catalog = 5;
  if (cached_has_bits & 0x00000002u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_name_in_catalog().data(), static_cast<int>(this->_internal_name_in_catalog().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "zetasql.SimpleTableProto.name_in_catalog");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_name_in_catalog(), target);
  }

  // optional bool allow_anonymous_column_name = 6;
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(6, this->_internal_allow_anonymous_column_name(), target);
  }

  // optional bool allow_duplicate_column_names = 7;
  if (cached_has_bits & 0x00000040u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(7, this->_internal_allow_duplicate_column_names(), target);
  }

  // optional .zetasql.SimpleAnonymizationInfoProto anonymization_info = 8;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        8, _Internal::anonymization_info(this), target, stream);
  }

  // repeated int32 primary_key_column_index = 9;
  for (int i = 0, n = this->_internal_primary_key_column_index_size(); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(9, this->_internal_primary_key_column_index(i), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:zetasql.SimpleTableProto)
  return target;
}

size_t SimpleTableProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:zetasql.SimpleTableProto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .zetasql.SimpleColumnProto column = 4;
  total_size += 1UL * this->_internal_column_size();
  for (const auto& msg : this->column_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated int32 primary_key_column_index = 9;
  {
    size_t data_size = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      Int32Size(this->primary_key_column_index_);
    total_size += 1 *
                  ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_primary_key_column_index_size());
    total_size += data_size;
  }

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    // optional string name = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_name());
    }

    // optional string name_in_catalog = 5;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_name_in_catalog());
    }

    // optional .zetasql.SimpleAnonymizationInfoProto anonymization_info = 8;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *anonymization_info_);
    }

    // optional int64 serialization_id = 2;
    if (cached_has_bits & 0x00000008u) {
      total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64SizePlusOne(this->_internal_serialization_id());
    }

    // optional bool is_value_table = 3;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + 1;
    }

    // optional bool allow_anonymous_column_name = 6;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 + 1;
    }

    // optional bool allow_duplicate_column_names = 7;
    if (cached_has_bits & 0x00000040u) {
      total_size += 1 + 1;
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SimpleTableProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SimpleTableProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SimpleTableProto::GetClassData() const { return &_class_data_; }

void SimpleTableProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<SimpleTableProto *>(to)->MergeFrom(
      static_cast<const SimpleTableProto &>(from));
}


void SimpleTableProto::MergeFrom(const SimpleTableProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:zetasql.SimpleTableProto)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  column_.MergeFrom(from.column_);
  primary_key_column_index_.MergeFrom(from.primary_key_column_index_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_name(from._internal_name());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_set_name_in_catalog(from._internal_name_in_catalog());
    }
    if (cached_has_bits & 0x00000004u) {
      _internal_mutable_anonymization_info()->::zetasql::SimpleAnonymizationInfoProto::MergeFrom(from._internal_anonymization_info());
    }
    if (cached_has_bits & 0x00000008u) {
      serialization_id_ = from.serialization_id_;
    }
    if (cached_has_bits & 0x00000010u) {
      is_value_table_ = from.is_value_table_;
    }
    if (cached_has_bits & 0x00000020u) {
      allow_anonymous_column_name_ = from.allow_anonymous_column_name_;
    }
    if (cached_has_bits & 0x00000040u) {
      allow_duplicate_column_names_ = from.allow_duplicate_column_names_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SimpleTableProto::CopyFrom(const SimpleTableProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:zetasql.SimpleTableProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SimpleTableProto::IsInitialized() const {
  if (!::PROTOBUF_NAMESPACE_ID::internal::AllAreInitialized(column_))
    return false;
  return true;
}

void SimpleTableProto::InternalSwap(SimpleTableProto* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  column_.InternalSwap(&other->column_);
  primary_key_column_index_.InternalSwap(&other->primary_key_column_index_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &name_, lhs_arena,
      &other->name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &name_in_catalog_, lhs_arena,
      &other->name_in_catalog_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SimpleTableProto, allow_duplicate_column_names_)
      + sizeof(SimpleTableProto::allow_duplicate_column_names_)
      - PROTOBUF_FIELD_OFFSET(SimpleTableProto, anonymization_info_)>(
          reinterpret_cast<char*>(&anonymization_info_),
          reinterpret_cast<char*>(&other->anonymization_info_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SimpleTableProto::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_zetasql_2fpublic_2fsimple_5ftable_2eproto_getter, &descriptor_table_zetasql_2fpublic_2fsimple_5ftable_2eproto_once,
      file_level_metadata_zetasql_2fpublic_2fsimple_5ftable_2eproto[1]);
}

// ===================================================================

class SimpleColumnProto::_Internal {
 public:
  using HasBits = decltype(std::declval<SimpleColumnProto>()._has_bits_);
  static void set_has_name(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::zetasql::TypeProto& type(const SimpleColumnProto* msg);
  static void set_has_type(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_is_pseudo_column(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_is_writable_column(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static const ::zetasql::AnnotationMapProto& annotation_map(const SimpleColumnProto* msg);
  static void set_has_annotation_map(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

const ::zetasql::TypeProto&
SimpleColumnProto::_Internal::type(const SimpleColumnProto* msg) {
  return *msg->type_;
}
const ::zetasql::AnnotationMapProto&
SimpleColumnProto::_Internal::annotation_map(const SimpleColumnProto* msg) {
  return *msg->annotation_map_;
}
void SimpleColumnProto::clear_type() {
  if (type_ != nullptr) type_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
void SimpleColumnProto::clear_annotation_map() {
  if (annotation_map_ != nullptr) annotation_map_->Clear();
  _has_bits_[0] &= ~0x00000004u;
}
SimpleColumnProto::SimpleColumnProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:zetasql.SimpleColumnProto)
}
SimpleColumnProto::SimpleColumnProto(const SimpleColumnProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_name()) {
    name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_name(), 
      GetArenaForAllocation());
  }
  if (from._internal_has_type()) {
    type_ = new ::zetasql::TypeProto(*from.type_);
  } else {
    type_ = nullptr;
  }
  if (from._internal_has_annotation_map()) {
    annotation_map_ = new ::zetasql::AnnotationMapProto(*from.annotation_map_);
  } else {
    annotation_map_ = nullptr;
  }
  ::memcpy(&is_pseudo_column_, &from.is_pseudo_column_,
    static_cast<size_t>(reinterpret_cast<char*>(&is_writable_column_) -
    reinterpret_cast<char*>(&is_pseudo_column_)) + sizeof(is_writable_column_));
  // @@protoc_insertion_point(copy_constructor:zetasql.SimpleColumnProto)
}

inline void SimpleColumnProto::SharedCtor() {
name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&type_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&is_pseudo_column_) -
    reinterpret_cast<char*>(&type_)) + sizeof(is_pseudo_column_));
is_writable_column_ = true;
}

SimpleColumnProto::~SimpleColumnProto() {
  // @@protoc_insertion_point(destructor:zetasql.SimpleColumnProto)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void SimpleColumnProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete type_;
  if (this != internal_default_instance()) delete annotation_map_;
}

void SimpleColumnProto::ArenaDtor(void* object) {
  SimpleColumnProto* _this = reinterpret_cast< SimpleColumnProto* >(object);
  (void)_this;
}
void SimpleColumnProto::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SimpleColumnProto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SimpleColumnProto::Clear() {
// @@protoc_insertion_point(message_clear_start:zetasql.SimpleColumnProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      name_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(type_ != nullptr);
      type_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(annotation_map_ != nullptr);
      annotation_map_->Clear();
    }
  }
  if (cached_has_bits & 0x00000018u) {
    is_pseudo_column_ = false;
    is_writable_column_ = true;
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SimpleColumnProto::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "zetasql.SimpleColumnProto.name");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .zetasql.TypeProto type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_type(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool is_pseudo_column = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _Internal::set_has_is_pseudo_column(&has_bits);
          is_pseudo_column_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool is_writable_column = 4 [default = true];
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _Internal::set_has_is_writable_column(&has_bits);
          is_writable_column_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .zetasql.AnnotationMapProto annotation_map = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_annotation_map(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SimpleColumnProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:zetasql.SimpleColumnProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "zetasql.SimpleColumnProto.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // optional .zetasql.TypeProto type = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::type(this), target, stream);
  }

  // optional bool is_pseudo_column = 3;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(3, this->_internal_is_pseudo_column(), target);
  }

  // optional bool is_writable_column = 4 [default = true];
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(4, this->_internal_is_writable_column(), target);
  }

  // optional .zetasql.AnnotationMapProto annotation_map = 5;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        5, _Internal::annotation_map(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:zetasql.SimpleColumnProto)
  return target;
}

size_t SimpleColumnProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:zetasql.SimpleColumnProto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    // optional string name = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_name());
    }

    // optional .zetasql.TypeProto type = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *type_);
    }

    // optional .zetasql.AnnotationMapProto annotation_map = 5;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *annotation_map_);
    }

    // optional bool is_pseudo_column = 3;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 1;
    }

    // optional bool is_writable_column = 4 [default = true];
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + 1;
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SimpleColumnProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SimpleColumnProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SimpleColumnProto::GetClassData() const { return &_class_data_; }

void SimpleColumnProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<SimpleColumnProto *>(to)->MergeFrom(
      static_cast<const SimpleColumnProto &>(from));
}


void SimpleColumnProto::MergeFrom(const SimpleColumnProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:zetasql.SimpleColumnProto)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_name(from._internal_name());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_mutable_type()->::zetasql::TypeProto::MergeFrom(from._internal_type());
    }
    if (cached_has_bits & 0x00000004u) {
      _internal_mutable_annotation_map()->::zetasql::AnnotationMapProto::MergeFrom(from._internal_annotation_map());
    }
    if (cached_has_bits & 0x00000008u) {
      is_pseudo_column_ = from.is_pseudo_column_;
    }
    if (cached_has_bits & 0x00000010u) {
      is_writable_column_ = from.is_writable_column_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SimpleColumnProto::CopyFrom(const SimpleColumnProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:zetasql.SimpleColumnProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SimpleColumnProto::IsInitialized() const {
  if (_internal_has_type()) {
    if (!type_->IsInitialized()) return false;
  }
  return true;
}

void SimpleColumnProto::InternalSwap(SimpleColumnProto* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &name_, lhs_arena,
      &other->name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SimpleColumnProto, is_pseudo_column_)
      + sizeof(SimpleColumnProto::is_pseudo_column_)
      - PROTOBUF_FIELD_OFFSET(SimpleColumnProto, type_)>(
          reinterpret_cast<char*>(&type_),
          reinterpret_cast<char*>(&other->type_));
  swap(is_writable_column_, other->is_writable_column_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SimpleColumnProto::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_zetasql_2fpublic_2fsimple_5ftable_2eproto_getter, &descriptor_table_zetasql_2fpublic_2fsimple_5ftable_2eproto_once,
      file_level_metadata_zetasql_2fpublic_2fsimple_5ftable_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace zetasql
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::zetasql::SimpleAnonymizationInfoProto* Arena::CreateMaybeMessage< ::zetasql::SimpleAnonymizationInfoProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::zetasql::SimpleAnonymizationInfoProto >(arena);
}
template<> PROTOBUF_NOINLINE ::zetasql::SimpleTableProto* Arena::CreateMaybeMessage< ::zetasql::SimpleTableProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::zetasql::SimpleTableProto >(arena);
}
template<> PROTOBUF_NOINLINE ::zetasql::SimpleColumnProto* Arena::CreateMaybeMessage< ::zetasql::SimpleColumnProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::zetasql::SimpleColumnProto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
